services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: email_forwarder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  email-forwarder:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
