"""add sender_id to rules

Revision ID: fcf877cb8c7a
Revises: 1d5bf493d2c7
Create Date: 2025-09-12 18:01:25.053934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf877cb8c7a'
down_revision: Union[str, Sequence[str], None] = '1d5bf493d2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('rules', 'sender_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('rules', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.create_foreign_key(None, 'rules', 'senders', ['sender_id'], ['id'])
    op.drop_column('rules', 'sender')
    op.alter_column('senders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_senders_id'), table_name='senders')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_senders_id'), 'senders', ['id'], unique=False)
    op.alter_column('senders', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('rules', sa.Column('sender', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.alter_column('rules', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('rules', 'sender_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('rules', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
